spring:
  datasource:
    url: jdbc:postgresql://172.17.0.2:5432/bluecoding
    username: blue_coding
    password: pairing_session
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        default_schema: pairingsession
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQL95Dialect
  liquibase:
    change-log: classpath:db/changelog.sql

logging:
  level:
    root: INFO

bluecoding:
  job:
    cron: 0 0/1 * * * ?